#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "defs.h"
#include "./utils/criarTabuleiro.c"
#include "./utils/popularTabuleiro.c"
#include "./utils/sortearMinas.c"
#include "./utils/verificarCasasAdjacentes.c"
#include "./utils/draw.c"
#include "./utils/tratarMensagemDeError.c"